### PR TITLE
fix:add regexp for uris and host filter when create route

### PR DESCRIPTION
**Pull request by lilien1010**
fix: https://github.com/apache/incubator-apisix-dashboard/issues/69

### CODE REVIEW

**Comment by juzhiyuan** [comment]
image

Please pay attention to console error :)

**Comment by juzhiyuan** [comment]
image

Also, some error occurred when selecting the null value.

**Comment by lilien1010** [comment]
@juzhiyuan  how to show the error case

**Comment by juzhiyuan** [comment]
> @juzhiyuan how to show the error case

clicking F12 to open Developer Tools if you use Chrome or Firefox

**Comment by lilien1010** [comment]
@juzhiyuan I mean the steps to make the error happen again, I made some changes to check the typeof elements of array

**Comment by juzhiyuan** [comment]
> @juzhiyuan I mean the steps to make the error happen again, I made some changes to check the typeof elements of array

Checking

**Pull request merged**
