### PR TITLE
feature: compatible development and deployment environment request

### PR DESCRIPTION
**Pull request by bzp2010**
Add a request path prefix to compatible development and deployment environment.
Prepare For CD #176

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Please rebase master so you could debug your changes on Netlify

**Comment by juzhiyuan** [comment]
Also, I think we should still keep the `api` prefix:
1. we may use Mock server in the future;
2. we need use `api` prefix to let some services know which request wants access API server. 🤔

**Comment by bzp2010** [comment]
[change here](https://github.com/apache/incubator-apisix-dashboard/pull/190/files#diff-084c3d9c2786b7cd963be84e40a38725R54)
The global request prefix is set here. The specific value is determined according to `process.env.NODE_ENV`. The `/api` will not be added forward in the deployment environment.
It won't interfere with the use of mock environment.

**Comment by juzhiyuan** [comment]
🤔that's to say... the request will add `api` prefix in development, but not in production? then how could we distinct which request is accessing the API server?

**Comment by bzp2010** [comment]
**For API server, using umi proxy to forward or request directly is transparent and will not affect API server.**

In development, we use `yarn run start` to start devServer, in there `process.env.NODE_ENV` value is `development`.
In deploy, we use `yarn run build` to compile, in there `process.env.NODE_ENV` value is `production`.
It will be automate completely.(Maybe)

**Comment by juzhiyuan** [comment]
from your code changes, the request will add `api` prefix in development mode, but not in production mode, for any of those two modes, we still need to provide some prefix for Nginx or other services to check which one is accessing API server 🤔

Maybe I misunderstand your thoughts, we could have a WeChat call when you have time :)

**Comment by bzp2010** [comment]
Yes, I also think we need to have in-depth communication on this issue. We can't accurately convey the original meaning by means of words.

Time can be today or tomorrow. I have free time at night.

**Comment by juzhiyuan** [comment]
OK, you can call me directly between 09:00 and 22:00 tomorrow :)

**Pull request closed without merging**
