### PR TITLE
feature: change login page

### PR DESCRIPTION
**Pull request by bzp2010**
> fix user login fake function
> fix i18n content in login page

> 修复用户登录模拟函数，使其不依赖mock内容
> 修复登录页面国际化文本

### CODE REVIEW

**Comment by juzhiyuan** [comment]
@bzp2010 Thanks for your contribution, BTW, would you love contributing to Next branch?

**Comment by bzp2010** [comment]
Yes, I'd like to make some contributions to help it become available as soon as possible.

**Comment by juzhiyuan** [comment]
Wow, could you add my wechat? JuShaoyao

**Comment by bzp2010** [comment]
Ok, I just sent friend request.

**Pull request merged**
